[package]
name = "fractal_synaesthesia"
version = "0.1.0"
edition = "2024"

[dependencies]
dashu-float = "0.4.3"
macroquad = { version = "0.4.14", features = ["audio"] }
num_cpus = "1.17.0"
smallvec = "1.15.1"
threadpool = "1.8.1"
egui = "0.31.1"
egui-macroquad = "0.17.3"
aubio-rs = {version="0.2", features=["builtin"]}
hound = "3.5"  # For reading WAV files
thiserror = "2.0.16"

[profile.dev]
opt-level = 3
