[package]
name = "fractal_synaesthesia"
version = "0.1.0"
edition = "2024"

[dependencies]
dashu-float = "0.4.3" # For arbitrary-precision floating point arithmetic
macroquad = { version = "0.4.14", default-features = false }
num_cpus = "1.17.0"
smallvec = "1.15.1"
threadpool = "1.8.1" 
egui = "0.31.1"
egui-macroquad = { version = "0.17.3", default-features = false }
aubio-rs = {version="0.2", features=["builtin"]}
hound = "3.5"  # For reading WAV files
thiserror = "2.0.16"
rfd = "0.16.0" # For file dialogs
futures = "0.3.31"
kira = "0.11.0" # For audio playback
dirs = "6.0.0"
ffmpeg-next = "8.0.0"
# For saving and loading configuration files
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[profile.dev]
opt-level = 3
